/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/646d9dcdc8a5f5bddbfac913.glb -o src/components/Avatar.jsx -r public
*/
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useControls, levaStore as store } from "leva";
import React, { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";

// --- FONCTION UTILITAIRE : Convertit le Base64 en Blob audio ---
const base64ToBlob = (base64) => {
  const byteCharacters = atob(base64);
  const byteNumbers = new Array(byteCharacters.length);
  for (let i = 0; i < byteCharacters.length; i++) {
    byteNumbers[i] = byteCharacters.charCodeAt(i);
  }
  const byteArray = new Uint8Array(byteNumbers);
  return new Blob([byteArray], { type: "audio/mpeg" });
};

export function Avatar(props) {
  // --- NOUVEAU STATE : Stocke l'URL temporaire de l'audio généré ---
  const [audioUrl, setAudioUrl] = useState(null); 

  const {
    playAudio,
    script,
    headFollow,
    smoothMorphTarget,
    morphTargetSmoothing,
    isGenerating,
    lipsyncGain = 1.2,
  } = useControls({
    playAudio: false,
    headFollow: true,
    smoothMorphTarget: true,
    morphTargetSmoothing: 0.5,
    script: {
      value: "aro",
      options: ["welcome", "pizzas", "aro"],
    },
    isGenerating: false,
    lipsyncGain: { value: 1.2, min: 1, max: 10, step: 0.1 },
  });

  // --- MODIFICATION : L'audio se crée à partir de l'URL Blob (si elle existe) ou d'un fichier par défaut ---
  const audio = useMemo(() => {
    // Si on a reçu un audio du backend, on l'utilise
    if (audioUrl) {
      const a = new Audio(audioUrl);
      a.volume = 1;
      return a;
    }
    // Sinon comportement par défaut (pour les tests locaux ou le démarrage)
    // Note: On évite de charger un fichier s'il n'y a pas d'URL générée pour éviter les 404
    return new Audio(); 
  }, [audioUrl]);

  // Refs pour Web Audio API
  const audioContextRef = useRef(null);
  const analyserRef = useRef(null);
  const sourceRef = useRef(null);
  const dataArrayRef = useRef(null);

  // Configuration AudioContext
  useEffect(() => {
    if (!audio.src) return; // Ne rien faire si pas de source audio

    const context = new (window.AudioContext || window.webkitAudioContext)();
    const analyser = context.createAnalyser();
    analyser.fftSize = 256;
    const bufferLength = analyser.frequencyBinCount;
    dataArrayRef.current = new Uint8Array(bufferLength);

    audioContextRef.current = context;
    analyserRef.current = analyser;

    // Gestion CORS si besoin (pas nécessaire pour Blob URL mais bonne pratique)
    audio.crossOrigin = "anonymous";

    try {
        const source = context.createMediaElementSource(audio);
        source.connect(analyser);
        analyser.connect(context.destination);
        sourceRef.current = source;
    } catch (e) {
        console.error("Erreur AudioContext:", e);
    }

    return () => {
      if (sourceRef.current) {
        // sourceRef.current.disconnect(); // Parfois cause des bugs de déconnexion, laisser le GC faire
      }
      if (context.state !== 'closed') context.close();
    };
  }, [audio]);

  const group = useRef();
  const { nodes, materials } = useGLTF("/models/aro.glb");

  // Animations FBX
  const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
  const { animations: angryAnimation } = useFBX("/animations/Angry Gesture.fbx");
  const { animations: greetingAnimation } = useFBX("/animations/Standing Greeting.fbx");
  const { animations: thinkingAnimation } = useFBX("/animations/Speak.fbx");
  const { animations: talkingAnimation } = useFBX("/animations/Talking.fbx");
  const { animations: reflAnimation } = useFBX("/animations/Refl.fbx");
  

  idleAnimation[0].name = "Idle";
  angryAnimation[0].name = "Angry";
  greetingAnimation[0].name = "Greeting";
  thinkingAnimation[0].name = "Think";
  talkingAnimation[0].name = "Talk";
  reflAnimation[0].name = "Refl";

  const [animation, setAnimation] = useState("Idle");
  const { actions, mixer } = useAnimations(
    [idleAnimation[0], angryAnimation[0], greetingAnimation[0], thinkingAnimation[0], talkingAnimation[0], reflAnimation[0]],
    group
  );

  // Lecture / Pause
  useEffect(() => {
    if (playAudio && audio.src) { // On vérifie qu'il y a une source
      audio.currentTime = 0;
      audio.play().catch(err => console.error("Erreur Play :", err));

      // Choix animation
      const anims = ["Think", "Talk"];
      const randomAnim = anims[Math.floor(Math.random() * anims.length)];
      setAnimation(randomAnim);
    } else {
      audio.pause();
      setAnimation("Idle");
    }
  }, [playAudio, audio]);

  // Lipsync
  useFrame(() => {
    // Si pas d'analyseur ou audio en pause, on reset la bouche et on arrête
    const head = nodes.Wolf3D_Head;
    const teeth = nodes.Wolf3D_Teeth;
    if (!head || !teeth) return;

    const dict = head.morphTargetDictionary;
    const visemeNames = ["viseme_PP", "viseme_kk", "viseme_I", "viseme_AA", "viseme_O", "viseme_U", "viseme_FF", "viseme_TH"];

    // Reset progressif (toujours exécuté pour fermer la bouche quand ça coupe)
    visemeNames.forEach((name) => {
        const idx = dict[name];
        if (idx !== undefined) {
            head.morphTargetInfluences[idx] = THREE.MathUtils.lerp(head.morphTargetInfluences[idx], 0, morphTargetSmoothing);
            teeth.morphTargetInfluences[idx] = THREE.MathUtils.lerp(teeth.morphTargetInfluences[idx], 0, morphTargetSmoothing);
        }
    });

    if (!analyserRef.current || audio.paused || audio.ended) return;

    const analyser = analyserRef.current;
    const dataArray = dataArrayRef.current;
    analyser.getByteFrequencyData(dataArray);

    const numBins = dataArray.length;
    const lowEnd = Math.floor(numBins * 0.15);
    const midEnd = Math.floor(numBins * 0.55);

    let lowAvg = 0;
    for (let i = 0; i < lowEnd; i++) lowAvg += dataArray[i];
    lowAvg = (lowAvg / lowEnd / 255) * lipsyncGain;

    let midAvg = 0;
    for (let i = lowEnd; i < midEnd; i++) midAvg += dataArray[i];
    midAvg = (midAvg / (midEnd - lowEnd) / 255) * lipsyncGain;

    let highAvg = 0;
    for (let i = midEnd; i < numBins; i++) highAvg += dataArray[i];
    highAvg = (highAvg / (numBins - midEnd) / 255) * lipsyncGain;

    const targets = {
      viseme_O: Math.min(1, lowAvg),
      viseme_U: Math.min(1, lowAvg * 0.8),
      viseme_AA: Math.min(1, midAvg),
      viseme_I: Math.min(1, highAvg),
      viseme_FF: Math.min(1, highAvg * 0.6),
      viseme_TH: Math.min(1, highAvg * 0.4),
      viseme_PP: Math.min(1, midAvg * 0.5),
      viseme_kk: Math.min(1, lowAvg * 0.5),
    };

    visemeNames.forEach((name) => {
      const target = targets[name] || 0;
      const idx = dict[name];
      if (idx !== undefined) {
        if (smoothMorphTarget) {
          head.morphTargetInfluences[idx] = THREE.MathUtils.lerp(head.morphTargetInfluences[idx], target, morphTargetSmoothing);
          teeth.morphTargetInfluences[idx] = THREE.MathUtils.lerp(teeth.morphTargetInfluences[idx], target, morphTargetSmoothing);
        } else {
          head.morphTargetInfluences[idx] = target;
          teeth.morphTargetInfluences[idx] = target;
        }
      }
    });
  });

  // Head follow
  useFrame((state) => {
    if (headFollow && group.current) {
      group.current.getObjectByName("Head").lookAt(state.camera.position);
    }
  });

  // Animation pendant "Generating" (réflexion)
  useEffect(() => {
    if (isGenerating) {
      audio.pause(); // Stop l'audio précédent si on génère
      setAnimation("Refl");
    }
  }, [isGenerating, audio]);

  // Gestion mixer animations
  useEffect(() => {
    const currentAction = actions[animation];
    if (currentAction) {
      currentAction.reset().fadeIn(0.5).play();
      if (animation === "Think" || animation === "Talk" || (animation === "Greeting" && !isGenerating)) {
        currentAction.loop = THREE.LoopOnce;
        currentAction.clampWhenFinished = true;
      } else {
        currentAction.loop = THREE.LoopRepeat;
      }
    }

    const onFinished = (e) => {
      // Relance une animation random si on est toujours en train de parler
      if (e.action === currentAction && !audio.paused && !audio.ended && (animation === "Talk" || animation === "Think")) {
        const anims = ["Think", "Talk"];
        const randomAnim = anims[Math.floor(Math.random() * anims.length)];
        setAnimation(randomAnim);
      }
    };
    mixer.addEventListener("finished", onFinished);

    return () => {
      if (currentAction) currentAction.fadeOut(0.5);
      mixer.removeEventListener("finished", onFinished);
    };
  }, [animation, actions, mixer, audio, isGenerating]);

  // Fin audio
  useEffect(() => {
    const onAudioEnd = () => {
        store.set({ playAudio: false });
        setAnimation("Idle");
    };
    audio.addEventListener("ended", onAudioEnd);
    return () => audio.removeEventListener("ended", onAudioEnd);
  }, [audio]);

  // --- RÉCEPTION DE L'AUDIO DEPUIS L'INTERFACE ---
  // C'est ici que la magie opère pour connecter le front au back
  useEffect(() => {
    const handleAudioGenerated = (e) => {
      // e.detail contient l'objet { audioBase64: "..." } envoyé par le composant UI
      if (e.detail && e.detail.audioBase64) {
        try {
            // 1. Convertir Base64 en Blob
            const blob = base64ToBlob(e.detail.audioBase64);
            // 2. Créer une URL pour ce Blob (ex: blob:http://localhost:5173/xyz...)
            const url = URL.createObjectURL(blob);
            
            // 3. Mettre à jour l'audio
            setAudioUrl(url);
            
            // 4. Lancer la lecture
            store.set({ playAudio: true });
        } catch (err) {
            console.error("Erreur conversion audio:", err);
        }
      }
    };
    
    window.addEventListener("audioGenerated", handleAudioGenerated);
    return () => window.removeEventListener("audioGenerated", handleAudioGenerated);
  }, []);

  return (
    <group {...props} dispose={null} ref={group}>
      <group name="Armature">
        <primitive object={nodes.Hips} />
      </group>
      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials['Wolf3D_Outfit_Bottom.001']} skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials['Wolf3D_Outfit_Footwear.001']} skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials['Wolf3D_Outfit_Top.001']} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair001.geometry} material={materials['Wolf3D_Hair.001']} skeleton={nodes.Wolf3D_Hair001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Glasses.geometry} material={materials.Wolf3D_Glasses} skeleton={nodes.Wolf3D_Glasses.skeleton} />
      <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  );
}

// Preload uniquement le modèle principal - les FBX se chargent à la demande
useGLTF.preload("/models/aro.glb");
